[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
mumbai = "https://polygon-mumbai.g.alchemy.com/v2/${MUMBAI_API_KEY}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
